kitchen_moves:
  - kitchen_arm/rest # Will manually place in rest at start but good safety
  - kitchen_arm/over_counter
  - kitchen_arm/over_sink
  - kitchen_gripper/open
  - kitchen_arm/into_sink
  - kitchen_gripper/close
  - kitchen_arm/over_sink_with_plate
  - kitchen_arm/over_dishwasher
  - kitchen_arm/into_dishwasher
  - kitchen_gripper/open
  - kitchen_arm/home
  - kitchen_arm/rest
left_arm: 
  rest: [0.0, -1.6, 1.5, 0.0, 0.4, 0.0, 4]
right_arm: 
  rest: [0.0, -1.6, 1.5, 0.0, 0.4, 0.0, 4]
left_gripper: # Gripper angle
  open: [0.0]
  close: [1.1]
right_gripper:
  open: [0.0]
  close: [1.1]