kitchen_moves:
  - kitchen_arm/rest # Will manually place in rest at start but good safety
  - kitchen_arm/over_counter
  - kitchen_arm/over_sink
  - kitchen_gripper/open
  - kitchen_arm/into_sink
  - kitchen_gripper/close
  - kitchen_arm/over_sink_with_plate
  - kitchen_arm/over_dishwasher
  - kitchen_arm/into_dishwasher
  - kitchen_gripper/open
  - kitchen_arm/home
  - kitchen_arm/rest
kitchen_arm: # Joints 1-6, path time to pose
  rest: [0.0, -1.6, 1.5, 0.0, 0.4, 0.0, 2.0]
  over_counter: [0.0, 0.0, 1.0, 0.0, 0.570, 0.0, 2.5]
  over_sink: [-0.509, 1.210, 0.022, -0.611, 1.570, -0.162, 2.0]
  into_sink: [-1.120, 1.384, 0.119, -1.134, 1.570, -0.542, 1.5] # 1.5
  over_sink_with_plate: [-0.429, 1.155, -0.126, -0.856, 1.500, -0.162, 1.5]
  over_dishwasher: [0.836, -0.077, 0.109, 0.056, 1.471, -0.162, 3.0]
  into_dishwasher: [1.389, -0.072, 0.118, 0.405, 1.468, -0.099, 1.5]
  home: [0.0, -0.785, 0.393, 0.0, 0.393, 0.0, 3.0]
kitchen_gripper: # Gripper angle
  open: [0.0]
  close: [1.13]