robot1: 5
robot2: 8

arm:
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 9982
  Profile_Velocity: 2900
  Homing_Offset: -125480
gripper:
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 9982
  Profile_Velocity: 2900

  # stand 1 nuc 3 left 2 right 3
  # stand 2 nuc 2 left 6 right 7
  # stand 3 nuc 4 left 1 right 4
  # stand 4 nuc 6 left 5 right 8
