# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  robotleft/gripper:
    has_velocity_limits: true
    max_velocity: 6.5
    has_acceleration_limits: false
    max_acceleration: 0
  robotleft/gripper_sub:
    has_velocity_limits: true
    max_velocity: 6.5
    has_acceleration_limits: false
    max_acceleration: 0
  robotleft/joint1:
    has_velocity_limits: true
    max_velocity: 6.5
    has_acceleration_limits: false
    max_acceleration: 0
  robotleft/joint2:
    has_velocity_limits: true
    max_velocity: 6.5
    has_acceleration_limits: false
    max_acceleration: 0
  robotleft/joint3:
    has_velocity_limits: true
    max_velocity: 6.5
    has_acceleration_limits: false
    max_acceleration: 0
  robotleft/joint4:
    has_velocity_limits: true
    max_velocity: 6.5
    has_acceleration_limits: false
    max_acceleration: 0
  robotleft/joint5:
    has_velocity_limits: true
    max_velocity: 6.5
    has_acceleration_limits: false
    max_acceleration: 0
  robotleft/joint6:
    has_velocity_limits: true
    max_velocity: 6.5
    has_acceleration_limits: false
    max_acceleration: 0
  robotright/gripper:
    has_velocity_limits: true
    max_velocity: 6.5
    has_acceleration_limits: false
    max_acceleration: 0
  robotright/gripper_sub:
    has_velocity_limits: true
    max_velocity: 6.5
    has_acceleration_limits: false
    max_acceleration: 0
  robotright/joint1:
    has_velocity_limits: true
    max_velocity: 6.5
    has_acceleration_limits: false
    max_acceleration: 0
  robotright/joint2:
    has_velocity_limits: true
    max_velocity: 6.5
    has_acceleration_limits: false
    max_acceleration: 0
  robotright/joint3:
    has_velocity_limits: true
    max_velocity: 6.5
    has_acceleration_limits: false
    max_acceleration: 0
  robotright/joint4:
    has_velocity_limits: true
    max_velocity: 6.5
    has_acceleration_limits: false
    max_acceleration: 0
  robotright/joint5:
    has_velocity_limits: true
    max_velocity: 6.5
    has_acceleration_limits: false
    max_acceleration: 0
  robotright/joint6:
    has_velocity_limits: true
    max_velocity: 6.5
    has_acceleration_limits: false
    max_acceleration: 0