right_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - right_arm/joint1
    - right_arm/joint2
    - right_arm/joint3
    - right_arm/joint4
    - right_arm/joint5
    - right_arm/joint6
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      right_arm/joint1: {trajectory: 0.1, goal: 0.1}
      right_arm/joint2: {trajectory: 0.1, goal: 0.1}
      right_arm/joint3: {trajectory: 0.1, goal: 0.1}
      right_arm/joint4: {trajectory: 0.1, goal: 0.1}
      right_arm/joint5: {trajectory: 0.1, goal: 0.1}
      right_arm/joint6: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10

left_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - left_arm/joint1
    - left_arm/joint2
    - left_arm/joint3
    - left_arm/joint4
    - left_arm/joint5
    - left_arm/joint6
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      left_arm/joint1: {trajectory: 0.1, goal: 0.1}
      left_arm/joint2: {trajectory: 0.1, goal: 0.1}
      left_arm/joint3: {trajectory: 0.1, goal: 0.1}
      left_arm/joint4: {trajectory: 0.1, goal: 0.1}
      left_arm/joint5: {trajectory: 0.1, goal: 0.1}
      left_arm/joint6: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10

right_gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - right_arm/gripper
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      right_arm/gripper: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
  gains: # Required because we're controlling an effort interface
    right_arm/gripper: {p: 100,  d: 1, i: 1, i_clamp: 1}

left_gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - left_arm/gripper
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      left_arm/gripper: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
  gains: # Required because we're controlling an effort interface
    left_arm/gripper: {p: 100,  d: 1, i: 1, i_clamp: 1}