right_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - robotright/joint1
    - robotright/joint2
    - robotright/joint3
    - robotright/joint4
    - robotright/joint5
    - robotright/joint6
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      robotright/joint1: {trajectory: 0.1, goal: 0.1}
      robotright/joint2: {trajectory: 0.1, goal: 0.1}
      robotright/joint3: {trajectory: 0.1, goal: 0.1}
      robotright/joint4: {trajectory: 0.1, goal: 0.1}
      robotright/joint5: {trajectory: 0.1, goal: 0.1}
      robotright/joint6: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10

left_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - robotleft/joint1
    - robotleft/joint2
    - robotleft/joint3
    - robotleft/joint4
    - robotleft/joint5
    - robotleft/joint6
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      robotleft/joint1: {trajectory: 0.1, goal: 0.1}
      robotleft/joint2: {trajectory: 0.1, goal: 0.1}
      robotleft/joint3: {trajectory: 0.1, goal: 0.1}
      robotleft/joint4: {trajectory: 0.1, goal: 0.1}
      robotleft/joint5: {trajectory: 0.1, goal: 0.1}
      robotleft/joint6: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10

# right_gripper_controller:
#   type: effort_controllers/JointTrajectoryController
#   joints:
#     - robotright/gripper
#   constraints:
#       goal_time: 0.6
#       stopped_velocity_tolerance: 0.05
#       robotright/gripper: {trajectory: 0.1, goal: 0.1}
#   stop_trajectory_duration: 0.5
#   state_publish_rate:  25
#   action_monitor_rate: 10
#   gains: # Required because we're controlling an effort interface
#     robotright/gripper: {p: 100,  d: 1, i: 1, i_clamp: 1}

# left_gripper_controller:
#   type: effort_controllers/JointTrajectoryController
#   joints:
#     - robotleft/gripper
#   constraints:
#       goal_time: 0.6
#       stopped_velocity_tolerance: 0.05
#       robotleft/gripper: {trajectory: 0.1, goal: 0.1}
#   stop_trajectory_duration: 0.5
#   state_publish_rate:  25
#   action_monitor_rate: 10
#   gains: # Required because we're controlling an effort interface
#     robotleft/gripper: {p: 100,  d: 1, i: 1, i_clamp: 1}