arm1_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - robot2/joint1
    - robot2/joint2
    - robot2/joint3
    - robot2/joint4
    - robot2/joint5
    - robot2/joint6
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      robot2/joint1: {trajectory: 0.1, goal: 0.1}
      robot2/joint2: {trajectory: 0.1, goal: 0.1}
      robot2/joint3: {trajectory: 0.1, goal: 0.1}
      robot2/joint4: {trajectory: 0.1, goal: 0.1}
      robot2/joint5: {trajectory: 0.1, goal: 0.1}
      robot2/joint6: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10

gripper1_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - robot2/gripper
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      robot2/gripper: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10