arm1_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - robot1/joint1
    - robot1/joint2
    - robot1/joint3
    - robot1/joint4
    - robot1/joint5
    - robot1/joint6
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      robot1/joint1: {trajectory: 0.1, goal: 0.1}
      robot1/joint2: {trajectory: 0.1, goal: 0.1}
      robot1/joint3: {trajectory: 0.1, goal: 0.1}
      robot1/joint4: {trajectory: 0.1, goal: 0.1}
      robot1/joint5: {trajectory: 0.1, goal: 0.1}
      robot1/joint6: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10

gripper1_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - robot1/jaw
    - robot1/pulley
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      robot1/jaw: {trajectory: 0.1, goal: 0.1}
      robot1/pulley: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
  gains: # Required because we're controlling an effort interface
    robot1/jaw: {p: 100,  d: 1, i: 1, i_clamp: 1}
    robot1/pulley: {p: 100,  d: 1, i: 1, i_clamp: 1}
