arm1_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - robot1/joint1
    - robot1/joint2
    - robot1/joint3
    - robot1/joint4
    - robot1/joint5
    - robot1/joint6
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10


gripper1_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - robot1/gripper
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
  gains: # Required because we're controlling an effort interface
    robot1/gripper: {p: 100,  d: 1, i: 1, i_clamp: 1}
