arm1_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - robot1/joint1
    - robot1/joint2
    - robot1/joint3
    - robot1/joint4
    - robot1/joint5
    - robot1/joint6
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      robot1/joint1: {trajectory: 0.1, goal: 0.1}
      robot1/joint2: {trajectory: 0.1, goal: 0.1}
      robot1/joint3: {trajectory: 0.1, goal: 0.1}
      robot1/joint4: {trajectory: 0.1, goal: 0.1}
      robot1/joint5: {trajectory: 0.1, goal: 0.1}
      robot1/joint6: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10

arm3_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - robot3/joint1
    - robot3/joint2
    - robot3/joint3
    - robot3/joint4
    - robot3/joint5
    - robot3/joint6
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      robot3/joint1: {trajectory: 0.1, goal: 0.1}
      robot3/joint2: {trajectory: 0.1, goal: 0.1}
      robot3/joint3: {trajectory: 0.1, goal: 0.1}
      robot3/joint4: {trajectory: 0.1, goal: 0.1}
      robot3/joint5: {trajectory: 0.1, goal: 0.1}
      robot3/joint6: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10

gripper1_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - robot1/gripper
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      robot1/gripper: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10

gripper3_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - robot3/gripper
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      robot3/gripper: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10