controller_list:
  - name: fake_arm2_controller
    type: $(arg fake_execution_type)
    joints:
      - robot2/joint1
      - robot2/joint2
      - robot2/joint3
      - robot2/joint4
      - robot2/joint5
      - robot2/joint6
  - name: fake_gripper2_controller
    type: $(arg fake_execution_type)
    joints:
      - robot2/gripper
initial:  # Define initial robot poses per group
  - group: arm2
    pose: rest
  - group: gripper2
    pose: open