controller_list:
  - name: arm2_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - robot2/joint1
      - robot2/joint2
      - robot2/joint3
      - robot2/joint4
      - robot2/joint5
      - robot2/joint6