# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm1
  joint_model_group_pose: init
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - robot1/joint1
    - robot1/joint2
    - robot1/joint3
    - robot1/joint4
    - robot1/joint5
    - robot1/joint6
    - robot2/joint1
    - robot2/joint2
    - robot2/joint3
    - robot2/joint4
    - robot2/joint5
    - robot2/joint6
    - robot3/joint1
    - robot3/joint2
    - robot3/joint3
    - robot3/joint4
    - robot3/joint5
    - robot3/joint6
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
arm_position_controller:
  type: position_controllers/JointPositionController
  joints:
    - robot1/joint1
    - robot1/joint2
    - robot1/joint3
    - robot1/joint4
    - robot1/joint5
    - robot1/joint6
    - robot2/joint1
    - robot2/joint2
    - robot2/joint3
    - robot2/joint4
    - robot2/joint5
    - robot2/joint6
    - robot3/joint1
    - robot3/joint2
    - robot3/joint3
    - robot3/joint4
    - robot3/joint5
    - robot3/joint6
  gains:
    robot1/joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot1/joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot1/joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot1/joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot1/joint5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot1/joint6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot2/joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot2/joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot2/joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot2/joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot2/joint5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot2/joint6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot3/joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot3/joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot3/joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot3/joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot3/joint5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot3/joint6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1