controller_list:
  - name: fake_arm1_controller
    type: $(arg execution_type)
    joints:
      - robot1/joint1
      - robot1/joint2
      - robot1/joint3
      - robot1/joint4
      - robot1/joint5
      - robot1/joint6
  - name: fake_arm2_controller
    type: $(arg execution_type)
    joints:
      - robot2/joint1
      - robot2/joint2
      - robot2/joint3
      - robot2/joint4
      - robot2/joint5
      - robot2/joint6
  - name: fake_arm3_controller
    type: $(arg execution_type)
    joints:
      - robot3/joint1
      - robot3/joint2
      - robot3/joint3
      - robot3/joint4
      - robot3/joint5
      - robot3/joint6
  - name: fake_arm4_controller
    type: $(arg execution_type)
    joints:
      - robot4/joint1
      - robot4/joint2
      - robot4/joint3
      - robot4/joint4
      - robot4/joint5
      - robot4/joint6
  - name: fake_arm1_2_controller
    type: $(arg execution_type)
    joints:
      - robot1/joint1
      - robot1/joint2
      - robot1/joint3
      - robot1/joint4
      - robot1/joint5
      - robot1/joint6
      - robot2/joint1
      - robot2/joint2
      - robot2/joint3
      - robot2/joint4
      - robot2/joint5
      - robot2/joint6
  - name: fake_arm2_3_controller
    type: $(arg execution_type)
    joints:
      - robot2/joint1
      - robot2/joint2
      - robot2/joint3
      - robot2/joint4
      - robot2/joint5
      - robot2/joint6
      - robot3/joint1
      - robot3/joint2
      - robot3/joint3
      - robot3/joint4
      - robot3/joint5
      - robot3/joint6
  - name: fake_arm1_3_controller
    type: $(arg execution_type)
    joints:
      - robot1/joint1
      - robot1/joint2
      - robot1/joint3
      - robot1/joint4
      - robot1/joint5
      - robot1/joint6
      - robot3/joint1
      - robot3/joint2
      - robot3/joint3
      - robot3/joint4
      - robot3/joint5
      - robot3/joint6
  - name: fake_arm3_4_controller
    type: $(arg execution_type)
    joints:
      - robot3/joint1
      - robot3/joint2
      - robot3/joint3
      - robot3/joint4
      - robot3/joint5
      - robot3/joint6
      - robot4/joint1
      - robot4/joint2
      - robot4/joint3
      - robot4/joint4
      - robot4/joint5
      - robot4/joint6
  - name: fake_arm1_4_controller
    type: $(arg execution_type)
    joints:
      - robot1/joint1
      - robot1/joint2
      - robot1/joint3
      - robot1/joint4
      - robot1/joint5
      - robot1/joint6
      - robot4/joint1
      - robot4/joint2
      - robot4/joint3
      - robot4/joint4
      - robot4/joint5
      - robot4/joint6
  - name: fake_arm1_2_3_controller
    type: $(arg execution_type)
    joints:
      - robot1/joint1
      - robot1/joint2
      - robot1/joint3
      - robot1/joint4
      - robot1/joint5
      - robot1/joint6
      - robot2/joint1
      - robot2/joint2
      - robot2/joint3
      - robot2/joint4
      - robot2/joint5
      - robot2/joint6
      - robot3/joint1
      - robot3/joint2
      - robot3/joint3
      - robot3/joint4
      - robot3/joint5
      - robot3/joint6
  - name: fake_arm1_2_4_controller
    type: $(arg execution_type)
    joints:
      - robot1/joint1
      - robot1/joint2
      - robot1/joint3
      - robot1/joint4
      - robot1/joint5
      - robot1/joint6
      - robot2/joint1
      - robot2/joint2
      - robot2/joint3
      - robot2/joint4
      - robot2/joint5
      - robot2/joint6
      - robot4/joint1
      - robot4/joint2
      - robot4/joint3
      - robot4/joint4
      - robot4/joint5
      - robot4/joint6
  - name: fake_arm1_2_3_4_controller
    type: $(arg execution_type)
    joints:
      - robot1/joint1
      - robot1/joint2
      - robot1/joint3
      - robot1/joint4
      - robot1/joint5
      - robot1/joint6
      - robot2/joint1
      - robot2/joint2
      - robot2/joint3
      - robot2/joint4
      - robot2/joint5
      - robot2/joint6
      - robot3/joint1
      - robot3/joint2
      - robot3/joint3
      - robot3/joint4
      - robot3/joint5
      - robot3/joint6
      - robot4/joint1
      - robot4/joint2
      - robot4/joint3
      - robot4/joint4
      - robot4/joint5
      - robot4/joint6
  - name: fake_gripper1_controller
    type: $(arg execution_type)
    joints:
      - robot1/gripper
  - name: fake_gripper4_controller
    type: $(arg execution_type)
    joints:
      - robot4/gripper
  - name: fake_gripper3_controller
    type: $(arg execution_type)
    joints:
      - robot3/gripper
  - name: fake_gripper3_4_controller
    type: $(arg execution_type)
    joints:
      - robot3/gripper
      - robot4/gripper
initial:  # Define initial robot poses.
  - group: arm1
    pose: rest
  - group: arm2
    pose: rest
  - group: arm3
    pose: rest
  - group: arm4
    pose: rest
  - group: arm1_2
    pose: rest
  - group: arm2_3
    pose: rest
  - group: arm1_3
    pose: rest
  - group: arm3_4
    pose: down
  - group: arm1_4
    pose: rest
  - group: arm1_2_3
    pose: rest
  - group: arm1_2_4
    pose: rest
  - group: arm1_2_3_4
    pose: rest
  - group: gripper1
    pose: open
  - group: gripper4
    pose: open
  - group: gripper3
    pose: open
  - group: gripper3_4
    pose: open