controller_list:
  - name: fake_arm3_controller
    type: $(arg execution_type)
    joints:
      - robot3/joint1
      - robot3/joint2
      - robot3/joint3
      - robot3/joint4
      - robot3/joint5
      - robot3/joint6
initial:  # Define initial robot poses.
 - group: arm3
   pose: rest