robotleft/joint1:
  ID: 7
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 300
  Profile_Velocity: 150
robotleft/joint2:
  ID: 8
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 300
  Profile_Velocity: 150
robotleft/joint3:
  ID: 9
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 300
  Profile_Velocity: 150
  Homing_Offset: -125480
robotleft/joint4:
  ID: 10
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 300
  Profile_Velocity: 150
robotleft/joint5:
  ID: 11
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 300
  Profile_Velocity: 150
robotleft/joint6:
  ID: 12
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 300
  Profile_Velocity: 150
robotleft/gripper:
  ID: 121
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 300
  Profile_Velocity: 150
robotright/joint1:
  ID: 13
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 300
  Profile_Velocity: 150
robotright/joint2:
  ID: 14
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 300
  Profile_Velocity: 150
robotright/joint3:
  ID: 15
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 300
  Profile_Velocity: 150
  Homing_Offset: -125480
robotright/joint4:
  ID: 16
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 300
  Profile_Velocity: 150
robotright/joint5:
  ID: 17
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 300
  Profile_Velocity: 150
robotright/joint6:
  ID: 18
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 300
  Profile_Velocity: 150
robotright/gripper:
  ID: 131
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 300
  Profile_Velocity: 150
