robotleft/joint1:
  ID: 1
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 3000
  Profile_Velocity: 1500
robotleft/joint2:
  ID: 2
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 3000
  Profile_Velocity: 1500
robotleft/joint3:
  ID: 3
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 3000
  Profile_Velocity: 1500
  Homing_Offset: -125480
robotleft/joint4:
  ID: 4
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 3000
  Profile_Velocity: 1500
robotleft/joint5:
  ID: 5
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 3000
  Profile_Velocity: 1500
robotleft/joint6:
  ID: 6
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 3000
  Profile_Velocity: 1500
# robot1/gripper:
#   ID: 111
#   Return_Delay_Time: 25
#   Acceleration_Limit: 9982
#   Velocity_Limit: 2900
#   Profile_Acceleration: 3000
#   Profile_Velocity: 1500
robotright/joint1:
  ID: 19
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 3000
  Profile_Velocity: 1500
robotright/joint2:
  ID: 20
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 3000
  Profile_Velocity: 1500
robotright/joint3:
  ID: 21
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 3000
  Profile_Velocity: 1500
  Homing_Offset: -125480
robotright/joint4:
  ID: 22
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 3000
  Profile_Velocity: 1500
robotright/joint5:
  ID: 23
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 3000
  Profile_Velocity: 1500
robotright/joint6:
  ID: 24
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 3000
  Profile_Velocity: 1500
# robot2/gripper:
#   ID: 141
#   Return_Delay_Time: 25
#   Acceleration_Limit: 9982
#   Velocity_Limit: 2900
#   Profile_Acceleration: 3000
#   Profile_Velocity: 1500
