robot3/joint1:
  ID: 1
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 200
  Profile_Velocity: 100
robot3/joint2:
  ID: 2
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 200
  Profile_Velocity: 100
robot3/joint3:
  ID: 3
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 200
  Profile_Velocity: 100
robot3/joint4:
  ID: 4
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 200
  Profile_Velocity: 100
robot3/joint5:
  ID: 5
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 200
  Profile_Velocity: 100
robot3/joint6:
  ID: 6
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 200
  Profile_Velocity: 100
robot3/gripper:
  ID: 111
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 300
  Profile_Velocity: 150