robot3/joint1:
  ID: 7
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 200
  Profile_Velocity: 100
robot3/joint2:
  ID: 8
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 200
  Profile_Velocity: 100
robot3/joint3:
  ID: 9
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 200
  Profile_Velocity: 100
robot3/joint4:
  ID: 10
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 200
  Profile_Velocity: 100
robot3/joint5:
  ID: 11
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 200
  Profile_Velocity: 100
robot3/joint6:
  ID: 12
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 200
  Profile_Velocity: 100