robot1/joint1:
  ID: 1
robot1/joint2:
  ID: 2
robot1/joint3:
  ID: 3
robot1/joint4:
  ID: 4
robot1/joint5:
  ID: 5
robot1/joint6:
  ID: 6

robot2/joint1:
  ID: 7
robot2/joint2:
  ID: 8
robot2/joint3:
  ID: 9
robot2/joint4:
  ID: 10
robot2/joint5:
  ID: 11
robot2/joint6:
  ID: 12

robot3/joint1:
  ID: 13
robot3/joint2:
  ID: 14
robot3/joint3:
  ID: 15
robot3/joint4:
  ID: 16
robot3/joint5:
  ID: 17
robot3/joint6:
  ID: 18
