# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm1_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    gripper1_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm1_controller:
  ros__parameters:
    joints:
      - robot1/joint1
      - robot1/joint2
      - robot1/joint3
      - robot1/joint4
      - robot1/joint5
      - robot1/joint6
      - robot1/joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      - effort
gripper1_controller:
  ros__parameters:
    joints:
      - robot1/gripper
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      - effort