controller_list:
  - name: fake_arm1_controller
    type: $(arg fake_execution_type)
    joints:
      - robot1/joint1
      - robot1/joint2
      - robot1/joint3
      - robot1/joint4
      - robot1/joint5
      - robot1/joint6
  - name: fake_arm3_controller
    type: $(arg fake_execution_type)
    joints:
      - robot3/joint1
      - robot3/joint2
      - robot3/joint3
      - robot3/joint4
      - robot3/joint5
      - robot3/joint6
  - name: fake_arm1_3_controller
    type: $(arg fake_execution_type)
    joints:
      - robot1/joint1
      - robot1/joint2
      - robot1/joint3
      - robot1/joint4
      - robot1/joint5
      - robot1/joint6
      - robot3/joint1
      - robot3/joint2
      - robot3/joint3
      - robot3/joint4
      - robot3/joint5
      - robot3/joint6
  - name: fake_gripper1_controller
    type: $(arg fake_execution_type)
    joints:
      - robot1/gripper
  - name: fake_gripper3_controller
    type: $(arg fake_execution_type)
    joints:
      - robot3/gripper
  - name: fake_gripper1_3_controller
    type: $(arg fake_execution_type)
    joints:
      - robot1/gripper
      - robot3/gripper
initial:  # Define initial robot poses per group
- group: arm1
    pose: init
  - group: arm3
    pose: init
  - group: arm1_3
    pose: init
  - group: gripper1
    pose: open
  - group: gripper3
    pose: open
  - group: gripper1_3
    pose: open