arm1_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - robot1/joint1
    - robot1/joint2
    - robot1/joint3
    - robot1/joint4
    - robot1/joint5
    - robot1/joint6
  gains:
    robot1/joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot1/joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot1/joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot1/joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot1/joint5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot1/joint6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
arm3_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - robot3/joint1
    - robot3/joint2
    - robot3/joint3
    - robot3/joint4
    - robot3/joint5
    - robot3/joint6
  gains:
    robot3/joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot3/joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot3/joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot3/joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot3/joint5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot3/joint6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
gripper1_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - robot1/gripper
  gains:
    robot1/gripper:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
gripper3_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - robot3/gripper
  gains:
    robot3/gripper:
      p: 100
      d: 1
      i: 1
      i_clamp: 1