robotleft/joint1:
  ID: 31
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 9982
  Profile_Velocity: 2900
robotleft/joint2:
  ID: 32
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 9982
  Profile_Velocity: 2900
robotleft/joint3:
  ID: 33
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 9982
  Profile_Velocity: 2900
  Homing_Offset: -125480
robotleft/joint4:
  ID: 34
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 9982
  Profile_Velocity: 2900
robotleft/joint5:
  ID: 35
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 9982
  Profile_Velocity: 2900
robotleft/joint6:
  ID: 36
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 9982
  Profile_Velocity: 2900
# robot1/gripper:
#   ID: 161
#   Return_Delay_Time: 25
#   Acceleration_Limit: 9982
#   Velocity_Limit: 2900
#   Profile_Acceleration: 9982
#   Profile_Velocity: 2900
robotright/joint1:
  ID: 37
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 9982
  Profile_Velocity: 2900
robotright/joint2:
  ID: 38
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 9982
  Profile_Velocity: 2900
robotright/joint3:
  ID: 39
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 9982
  Profile_Velocity: 2900
  Homing_Offset: -125480
robotright/joint4:
  ID: 40
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 9982
  Profile_Velocity: 2900
robotright/joint5:
  ID: 41
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 9982
  Profile_Velocity: 2900
robotright/joint6:
  ID: 42
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 9982
  Profile_Velocity: 2900
# robot2/gripper:
#   ID: 171
#   Return_Delay_Time: 25
#   Acceleration_Limit: 9982
#   Velocity_Limit: 2900
#   Profile_Acceleration: 9982
#   Profile_Velocity: 2900
