robot3/joint1:
  ID: 19
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 5000
  Profile_Velocity: 2500
robot3/joint2:
  ID: 20
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 5000
  Profile_Velocity: 2500
robot3/joint3:
  ID: 21
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 5000
  Profile_Velocity: 2500
  Homing_Offset: -125480
robot3/joint4:
  ID: 22
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 5000
  Profile_Velocity: 2500
robot3/joint5:
  ID: 23
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 5000
  Profile_Velocity: 2500
robot3/joint6:
  ID: 24
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 5000
  Profile_Velocity: 2500
robot3/gripper:
  ID: 141
  Return_Delay_Time: 25
  Operating_Mode: 5
  Current_Limit: 100
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 5000
  Profile_Velocity: 2500