robot1/joint1:
  ID: 1
  Return_Delay_Time: 25
  Operating_Mode: 3
  Profile_Acceleration: 100
  Profile_Velocity: 50
robot1/joint2:
  ID: 2
  Return_Delay_Time: 25
  Operating_Mode: 3
  Profile_Acceleration: 100
  Profile_Velocity: 50
robot1/joint3:
  ID: 3
  Return_Delay_Time: 25
  Operating_Mode: 3
  Profile_Acceleration: 100
  Profile_Velocity: 50
robot1/joint4:
  ID: 4
  Return_Delay_Time: 25
  Operating_Mode: 3
  Profile_Acceleration: 100
  Profile_Velocity: 50
robot1/joint5:
  ID: 5
  Return_Delay_Time: 25
  Operating_Mode: 3
  Profile_Acceleration: 100
  Profile_Velocity: 50
robot1/joint6:
  ID: 6
  Return_Delay_Time: 25
  Operating_Mode: 3
  Profile_Acceleration: 100
  Profile_Velocity: 50
robot1/gripper:
  ID: 111
  Return_Delay_Time: 25
  Operating_Mode: 3
  Profile_Acceleration: 100
  Profile_Velocity: 50

robot2/joint1:
  ID: 7
  Return_Delay_Time: 25
  Operating_Mode: 3
  Profile_Acceleration: 100
  Profile_Velocity: 50
robot2/joint2:
  ID: 8
  Return_Delay_Time: 25
  Operating_Mode: 3
  Profile_Acceleration: 100
  Profile_Velocity: 50
robot2/joint3:
  ID: 9
  Return_Delay_Time: 25
  Operating_Mode: 3
  Profile_Acceleration: 100
  Profile_Velocity: 50
robot2/joint4:
  ID: 10
  Return_Delay_Time: 25
  Operating_Mode: 3
  Profile_Acceleration: 100
  Profile_Velocity: 50
robot2/joint5:
  ID: 11
  Return_Delay_Time: 25
  Operating_Mode: 3
  Profile_Acceleration: 100
  Profile_Velocity: 50
robot2/joint6:
  ID: 12
  Return_Delay_Time: 25
  Operating_Mode: 3
  Profile_Acceleration: 100
  Profile_Velocity: 50
robot2/gripper:
  ID: 121
  Return_Delay_Time: 25
  Operating_Mode: 3
  Profile_Acceleration: 100
  Profile_Velocity: 50

robot3/joint1:
  ID: 13
  Return_Delay_Time: 25
  Operating_Mode: 3
  Profile_Acceleration: 100
  Profile_Velocity: 50
robot3/joint2:
  ID: 14
  Return_Delay_Time: 25
  Operating_Mode: 3
  Profile_Acceleration: 100
  Profile_Velocity: 50
robot3/joint3:
  ID: 15
  Return_Delay_Time: 25
  Operating_Mode: 3
  Profile_Acceleration: 100
  Profile_Velocity: 50
robot3/joint4:
  ID: 16
  Return_Delay_Time: 25
  Operating_Mode: 3
  Profile_Acceleration: 100
  Profile_Velocity: 50
robot3/joint5:
  ID: 17
  Return_Delay_Time: 25
  Operating_Mode: 3
  Profile_Acceleration: 100
  Profile_Velocity: 50
robot3/joint6:
  ID: 18
  Return_Delay_Time: 25
  Operating_Mode: 3
  Profile_Acceleration: 100
  Profile_Velocity: 50
robot3/gripper:
  ID: 131
  Return_Delay_Time: 25
  Profile_Acceleration: 50
  Profile_Velocity: 25