robot1/joint1:
  ID: 31
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 6000
  Profile_Velocity: 2900
robot1/joint2:
  ID: 32
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 6000
  Profile_Velocity: 2900
robot1/joint3:
  ID: 33
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 6000
  Profile_Velocity: 2900
  Homing_Offset: -125480
robot1/joint4:
  ID: 34
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 6000
  Profile_Velocity: 2900
robot1/joint5:
  ID: 35
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 6000
  Profile_Velocity: 2900
robot1/joint6:
  ID: 36
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 6000
  Profile_Velocity: 2900
robot1/gripper:
  ID: 161
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 6000
  Profile_Velocity: 2900