robot1/joint1:
  ID: 1
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 5000
  Profile_Velocity: 2500
robot1/joint2:
  ID: 2
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 5000
  Profile_Velocity: 2500
robot1/joint3:
  ID: 3
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 5000
  Profile_Velocity: 2500
  Homing_Offset: -125480
robot1/joint4:
  ID: 4
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 5000
  Profile_Velocity: 2500
robot1/joint5:
  ID: 5
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 5000
  Profile_Velocity: 2500
robot1/joint6:
  ID: 6
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 5000
  Profile_Velocity: 2500
robot1/gripper:
  ID: 111
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 5000
  Profile_Velocity: 2500
robot2/joint1:
  ID: 7
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 5000
  Profile_Velocity: 2500
robot2/joint2:
  ID: 8
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 5000
  Profile_Velocity: 2500
robot2/joint3:
  ID: 9
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 5000
  Profile_Velocity: 2500
  Homing_Offset: -125480
robot2/joint4:
  ID: 10
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 5000
  Profile_Velocity: 2500
robot2/joint5:
  ID: 11
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 5000
  Profile_Velocity: 2500
robot2/joint6:
  ID: 12
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 5000
  Profile_Velocity: 2500
robot2/gripper:
  ID: 121
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 5000
  Profile_Velocity: 2500
robot3/joint1:
  ID: 25
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 5000
  Profile_Velocity: 2500
robot3/joint2:
  ID: 26
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 5000
  Profile_Velocity: 2500
robot3/joint3:
  ID: 27
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 5000
  Profile_Velocity: 2500
  Homing_Offset: -125480
robot3/joint4:
  ID: 28
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 5000
  Profile_Velocity: 2500
robot3/joint5:
  ID: 29
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 5000
  Profile_Velocity: 2500
robot3/joint6:
  ID: 30
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 5000
  Profile_Velocity: 2500
robot3/gripper:
  ID: 151
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 5000
  Profile_Velocity: 2500
robot4/joint1:
  ID: 31
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 5000
  Profile_Velocity: 2500
robot4/joint2:
  ID: 32
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 5000
  Profile_Velocity: 2500
robot4/joint3:
  ID: 33
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 5000
  Profile_Velocity: 2500
  Homing_Offset: -125480
robot4/joint4:
  ID: 34
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 5000
  Profile_Velocity: 2500
robot4/joint5:
  ID: 35
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 5000
  Profile_Velocity: 2500
robot4/joint6:
  ID: 36
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 5000
  Profile_Velocity: 2500
robot4/gripper:
  ID: 161
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 5000
  Profile_Velocity: 2500
