robot1/joint1:
  ID: 1
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 1500
  Profile_Velocity: 750
robot1/joint2:
  ID: 2
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 1500
  Profile_Velocity: 750
robot1/joint3:
  ID: 3
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 1500
  Profile_Velocity: 750
  Homing_Offset: -125480
robot1/joint4:
  ID: 4
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 1500
  Profile_Velocity: 750
robot1/joint5:
  ID: 5
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 1500
  Profile_Velocity: 750
robot1/joint6:
  ID: 6
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 1500
  Profile_Velocity: 750
robot1/gripper:
  ID: 111
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 6000
  Profile_Velocity: 2900