robot1/joint1:
  ID: 37
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 5000
  Profile_Velocity: 2500
robot1/joint2:
  ID: 38
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 5000
  Profile_Velocity: 2500
robot1/joint3:
  ID: 39
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 5000
  Profile_Velocity: 2500
  Homing_Offset: -125480
robot1/joint4:
  ID: 40
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 5000
  Profile_Velocity: 2500
robot1/joint5:
  ID: 41
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 5000
  Profile_Velocity: 2500
robot1/joint6:
  ID: 42
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 5000
  Profile_Velocity: 2500