robot1/joint1:
  ID: 13
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 3000
  Profile_Velocity: 1500
robot1/joint2:
  ID: 14
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 3000
  Profile_Velocity: 1500
robot1/joint3:
  ID: 15
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 3000
  Profile_Velocity: 1500
  Homing_Offset: -125480
robot1/joint4:
  ID: 16
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 3000
  Profile_Velocity: 1500
robot1/joint5:
  ID: 17
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 3000
  Profile_Velocity: 1500
robot1/joint6:
  ID: 18
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 3000
  Profile_Velocity: 1500
robot1/gripper:
  ID: 131
  Return_Delay_Time: 25
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 3000
  Profile_Velocity: 1500