robot3/joint1:
  ID: 43
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 200
  Profile_Velocity: 100
robot3/joint2:
  ID: 44
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 200
  Profile_Velocity: 100
robot3/joint3: 
  ID: 45
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 200
  Profile_Velocity: 100
  Homing_Offset: -125480
robot3/joint4:
  ID: 46
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 200
  Profile_Velocity: 100
robot3/joint5:
  ID: 47
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 200
  Profile_Velocity: 100
robot3/joint6:
  ID: 48
  Return_Delay_Time: 25
  Operating_Mode: 3
  Acceleration_Limit: 9982
  Velocity_Limit: 2900
  Profile_Acceleration: 200
  Profile_Velocity: 100