controller_list:
  - name: fake_arm1_controller
    type: $(arg fake_execution_type)
    joints:
      - robot1/joint1
      - robot1/joint2
      - robot1/joint3
      - robot1/joint4
      - robot1/joint5
      - robot1/joint6
  - name: fake_arm2_controller
    type: $(arg fake_execution_type)
    joints:
      - robot2/joint1
      - robot2/joint2
      - robot2/joint3
      - robot2/joint4
      - robot2/joint5
      - robot2/joint6
  - name: fake_arm1_2_controller
    type: $(arg fake_execution_type)
    joints:
      - robot1/joint1
      - robot1/joint2
      - robot1/joint3
      - robot1/joint4
      - robot1/joint5
      - robot1/joint6
      - robot2/joint1
      - robot2/joint2
      - robot2/joint3
      - robot2/joint4
      - robot2/joint5
      - robot2/joint6
  - name: fake_gripper1_controller
    type: $(arg fake_execution_type)
    joints:
      - robot1/gripper
  - name: fake_gripper2_controller
    type: $(arg fake_execution_type)
    joints:
      - robot2/gripper
  - name: fake_gripper1_2_controller
    type: $(arg fake_execution_type)
    joints:
      - robot1/gripper
      - robot2/gripper
initial:  # Define initial robot poses.
  - group: arm1
    pose: rest
  - group: arm2
    pose: rest
  - group: arm1_2
    pose: rest
  - group: gripper1
    pose: open
  - group: gripper2
    pose: open
  - group: gripper1_2
    pose: open