#!/bin/bash

echo ""
echo "This script copies a udev rule to /etc to facilitate bringing"
echo "up the PAPRAS usb connection."
echo ""

sudo cp `ros2 pkg prefix papras_controls`/share/papras_controls/99-papras-cdc.rules /etc/udev/rules.d/


echo ""
echo "Reload rules"
echo ""
sudo udevadm control --reload-rules
sudo udevadm trigger
