controller_list:
  - name: fake_left_arm_controller
    type: $(arg execution_type)
    joints:
      - robotleft/joint1
      - robotleft/joint2
      - robotleft/joint3
      - robotleft/joint4
      - robotleft/joint5
      - robotleft/joint6
  - name: fake_right_arm_controller
    type: $(arg execution_type)
    joints:
      - robotright/joint1
      - robotright/joint2
      - robotright/joint3
      - robotright/joint4
      - robotright/joint5
      - robotright/joint6
  - name: fake_both_arms_controller
    type: $(arg execution_type)
    joints:
      - robotleft/joint1
      - robotleft/joint2
      - robotleft/joint3
      - robotleft/joint4
      - robotleft/joint5
      - robotleft/joint6
      - robotright/joint1
      - robotright/joint2
      - robotright/joint3
      - robotright/joint4
      - robotright/joint5
      - robotright/joint6
  - name: fake_left_gripper_controller
    type: $(arg execution_type)
    joints:
      - robotleft/gripper
  - name: fake_right_gripper_controller
    type: $(arg execution_type)
    joints:
      - robotright/gripper
initial:  # Define initial robot poses.
  - group: left_arm
    pose: init
  - group: right_arm
    pose: init
  - group: both_arms
    pose: init
  - group: left_gripper
    pose: open
  - group: right_gripper
    pose: open