# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: left_arm
  joint_model_group_pose: init
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - robotleft/joint1
    - robotleft/joint2
    - robotleft/joint3
    - robotleft/joint4
    - robotleft/joint5
    - robotleft/joint6
    # - robotleft/gripper
    - robotright/joint1
    - robotright/joint2
    - robotright/joint3
    - robotright/joint4
    - robotright/joint5
    - robotright/joint6
    - robotright/gripper
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: left_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - robotleft/joint1
      - robotleft/joint2
      - robotleft/joint3
      - robotleft/joint4
      - robotleft/joint5
      - robotleft/joint6
  - name: right_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - robotright/joint1
      - robotright/joint2
      - robotright/joint3
      - robotright/joint4
      - robotright/joint5
      - robotright/joint6
  # - name: left_gripper_controller
  #   action_ns: follow_joint_trajectory
  #   default: True
  #   type: FollowJointTrajectory
  #   joints:
  #     - robotleft/gripper
  - name: right_gripper_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - robotright/gripper