arm2_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - robot2/joint1
    - robot2/joint2
    - robot2/joint3
    - robot2/joint4
    - robot2/joint5
    - robot2/joint6
  gains:
    robot2/joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot2/joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot2/joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot2/joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot2/joint5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot2/joint6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
gripper2_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - robot2/gripper
  gains:
    robot2/gripper:
      p: 100
      d: 1
      i: 1
      i_clamp: 1