arm1_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - robot1/joint1
    - robot1/joint2
    - robot1/joint3
    - robot1/joint4
    - robot1/joint5
    - robot1/joint6
  gains:
    robot1/joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot1/joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot1/joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot1/joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot1/joint5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot1/joint6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
gripper1_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - robot1/jaw
    - robot1/pulley
  gains:
    robot1/jaw:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot1/pulley:
      p: 100
      d: 1
      i: 1
      i_clamp: 1