controller_list:
  - name: arm1_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - robot1/joint1
      - robot1/joint2
      - robot1/joint3
      - robot1/joint4
      - robot1/joint5
      - robot1/joint6
  - name: gripper1_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - robot1/jaw
      - robot1/pulley