controller_list:
  - name: fake_arm1_controller
    type: $(arg fake_execution_type)
    joints:
      - robot1/joint1
      - robot1/joint2
      - robot1/joint3
      - robot1/joint4
      - robot1/joint5
      - robot1/joint6
  - name: fake_gripper1_controller
    type: $(arg fake_execution_type)
    joints:
      - robot1/gripper
initial:  # Define initial robot poses per group
  - group: arm1
    pose: init
  - group: gripper1
    pose: open